[package]
name = "utena"
version = "0.3.4"
authors = ["ShootingStarDragons <ShootingStarDragons@protonmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "0.3.5"
gio = "0.17.4"
regex = "1"
once_cell = "1.17.1"
anyhow = "1.0.70"
zbus = "3"
deunicode = "1.3.3"

[build-dependencies]
slint-build = "0.3"
