[package]
name = "utena"
version = "0.4.1"
authors = ["ShootingStarDragons <ShootingStarDragons@protonmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.1.0"
gio = "0.17.10"
regex = "1"
once_cell = "1.18.0"
anyhow = "1.0.71"
zbus = "3.13.1"
deunicode = "1.3.3"
xdg = "2.5.0"

[build-dependencies]
slint-build = "1.1"
