[package]
name = "utena"
version = "0.3.2"
authors = ["ShootingStarDragons <ShootingStarDragons@protonmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "0.3.2"
gio = "0.16.3"
regex = "1"
once_cell = "1.16.0"
anyhow = "1.0.66"
zbus = "3"
deunicode = "1.3.2"

[build-dependencies]
slint-build = "0.3"
