[package]
name = "utena"
version = "0.2.0"
authors = ["ShootingStarDragons <ShootingStarDragons@protonmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "0.3"
gio = "0.15.12"
regex = "1"
once_cell = "1.15.0"
anyhow = "1.0.65"

[build-dependencies]
slint-build = "0.3"
