[package]
name = "utena"
version = "0.4.6"
authors = ["ShootingStarDragons <ShootingStarDragons@protonmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.3.0"
gio = "0.18.3"
regex = "1"
once_cell = "1.18.0"
anyhow = "1.0.75"
zbus = "3.14.1"
deunicode = "1.4.1"
xdg = "2.5.2"

[build-dependencies]
slint-build = "1.3"
